import { sqliteTable, text, integer} from 'drizzle-orm/sqlite-core';
export const setting = sqliteTable('setting', {
	register: integer('register').default(0).notNull(),
	receive: integer('receive').default(0).notNull(),
	title: text('title').default('FlareMail').notNull(),
	manyEmail: integer('many_email').default(0).notNull(),
	addEmail: integer('add_email').default(0).notNull(),
	autoRefresh: integer('auto_refresh').default(0).notNull(),
	addEmailVerify: integer('add_email_verify').default(1).notNull(),
	registerVerify: integer('register_verify').default(1).notNull(),
	addVerifyCount: integer('add_verify_count').default(1).notNull(),
	send: integer('send').default(1).notNull(),
	r2Domain: text('r2_domain'),
	secretKey: text('secret_key'),
	siteKey: text('site_key'),
	forwardEmail: text('forward_email').default('').notNull(),
	forwardStatus: integer('forward_status').default(1).notNull(),
	resendTokens: text('resend_tokens').default("{}").notNull(),
	noRecipient: integer('no_recipient').default(1).notNull(),
	loginDomain: integer('login_domain').default(0).notNull(),
	blackSubject: text('black_subject').default('').notNull(),
	blackContent: text('black_content').default('').notNull(),
	blackFrom: text('black_from').default('').notNull(),
	background: text('background'),
	loginOpacity: integer('login_opacity').default(0.90).notNull(),
	googleOauthEnabled: integer('google_oauth_enabled').default(0).notNull(),
	googleClientId: text('google_client_id').default('').notNull(),
	googleClientSecret: text('google_client_secret').default('').notNull(),
	siteDescription: text('site_description').default('').notNull(),
	siteLogo: text('site_logo').default('').notNull(),
	siteFavicon: text('site_favicon').default('').notNull(),
	sitePwaIcons: text('site_pwa_icons').default('{}').notNull(),
	loginCopy: text('login_copy').default('{}').notNull(),
	oauthProviderEnabled: integer('oauth_provider_enabled').default(0).notNull(),
	oauthProviderRevision: integer('oauth_provider_revision').default(0).notNull(),
	oauthProviderClients: text('oauth_provider_clients').default('[]').notNull()
});
export default setting
